notifications:
  email: false

# Only activate upon master/PR
branches:
  only:
    - master

language: python

python:
  - "3.6"

# env:
#   - ENV=Value

install:
  - make install

script:
  - make test
