DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Post;

CREATE TABLE User (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserName TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE Post (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  AuthorId INTEGER NOT NULL,
  CreatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Title TEXT NOT NULL,
  Body TEXT NOT NULL,
  FOREIGN KEY (AuthorId) REFERENCES User (id)
);
